# 异常处理

## 常见的异常分类 <a id="&#x5E38;&#x89C1;&#x7684;&#x5F02;&#x5E38;&#x5206;&#x7C7B;"></a>

* 运行环境的多样性导致的异常（浏览器）
* 语法错误，代码错误

异常最大的特征，就是一旦代码出现异常，后面的代码就不会再执行

## 异常捕获 <a id="&#x5F02;&#x5E38;&#x6355;&#x83B7;"></a>

捕获异常，使用`try-catch`语句

```text
try
{

//这里写可能出现异常的代码

}
catch
(e){

//这里的e就是捕获的异常对象
//可以在这里写，出现异常后的处理代码

}
```

异常捕获语句执行的过程为：

1. 代码正常运行, 如果在try中出现了错误, try 里面出现错误的语句后面的代码都不再执行, 直接跳转到 catch 中
2. catch中处理错误信息
3. 然后继续执行后面的代码
4. 如果 try 中没有出现错误, 那么不走 catch 直接执行后面的代码

通过`try-catch`语句进行异常捕获之后，代码将会继续执行，而不会中断。

**注意：**

* 语法错误异常用

  `try-catch`

  语句无法捕获，因为在预解析阶段，语法错误会直接检测出来，而不会等到运行的时候才报错。

* try-catch在一般日常开发中基本用不到，但是如果要写框架什么的，用的会非常多。因为这个会让框架变得健壮

## 抛出异常 <a id="&#x629B;&#x51FA;&#x5F02;&#x5E38;"></a>

如何手动的抛出异常呢？

> 案例：自己写的一个函数，需要一个参数，如果用户不传参数，此时想直接给用户抛出异常，就需要了解如何抛出异常。

抛出异常使用`throw`关键字，语法如下：

```text
throw
 异常对象;
```

异常对象一般是用`new Error("异常消息")`, 也可以使用任意对象

```text
function
test
(
para
)
{

if
(para == 
undefined
){

throw
new
Error
(
"请传递参数"
);

//这里也可以使用自定义的对象
throw
 {
"id"
:
1
, msg:
"参数未传递"
};
    }
}


try
{
    test();
}
catch
(e){

console
.log(e);
}
```

## 异常的传递机制 <a id="&#x5F02;&#x5E38;&#x7684;&#x4F20;&#x9012;&#x673A;&#x5236;"></a>

```text
function
f1
 (
) 
{
    f2(); 
// f1 称为调用者, 或主调函数, f2 称为被调用者, 或被调函数

}


function
f2
 (
) 
{
    f3();
}


function
f3
(
) 
{

throw
new
Error
( 
'error'
 );
}
f1();
```

当在被调函数内发生异常的时候，异常会一级一级往上抛出。

## 异常捕获语句的完整模式 <a id="&#x5F02;&#x5E38;&#x6355;&#x83B7;&#x8BED;&#x53E5;&#x7684;&#x5B8C;&#x6574;&#x6A21;&#x5F0F;"></a>

异常捕获语句的完整模式为`try-catch-finally`

```text
try
 {

//可能出现错误的代码

} 
catch
 ( e ) {

//如果出现错误就执行

} 
finally
 {

//结束 try 这个代码块之前执行, 即最后执行

}
```

`finally`中的代码，不管有没有发生异常，都会执行。一般用在后端语言中，用来释放资源，JavaScript中很少会用到

